import Head from "next/head";
import { Rubik } from "next/font/google";
import clsx from "clsx";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";

const MyIframe = dynamic(() => import("./../components/iframe"), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});

const font = Rubik({
  subsets: ["latin-ext"],
});

export default function Home() {
  const [show, setShow] = useState(false);
  useEffect(() => {
    setTimeout(() => {
      setShow(true);
    }, 1000);
  }, []);
  return (
    <div>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx("flex min-h-screen flex-col", font.className)}>
        <nav className="bg-sky-100 px-20 py-4">
          <h2 className="text-xl font-semibold">
            Parent App -{" "}
            <span className="inline-block rounded bg-gray-300 px-2 py-0.5 font-mono text-gray-700">
              Reverse Proxy
            </span>
          </h2>
        </nav>
        <section className="grow bg-green-50 px-20 py-4">
          {show && <MyIframe />}
        </section>
      </main>
    </div>
  );
}
